### ISSUE TITLE
Charging Time Walkthrough

### ISSUE THREAD

**Issue by mattzollinhofer** [iotait/apprenticeship#13]
I want to walk you through our timesheet and charging process: https://iotait.tsheets.com

**Comment by mattzollinhofer** [comment]
talked through this with Tanner. Need to make sure he gets a login to tsheets: https://iotait.tsheets.com/

**Comment by mattzollinhofer** [comment]
@tannerwernecke if you don't have a login by wednesday let me know and I'll make sure you get one.

**Comment by tannerwernecke** [comment]
@mattzollinhofer I still have not received a login for tsheets.

**Comment by mattzollinhofer** [comment]
@tannerwernecke I think you should be all set, sounds like David sent you a login, let me know if you didn't get it.
