### ISSUE TITLE
Rails Getting Started Tutorial

### ISSUE THREAD

**Issue by mattzollinhofer** [iotait/apprenticeship#14]
https://www.railstutorial.org/book

**Comment by tannerwernecke** [comment]
Finished Monday (11/4) at:
https://www.railstutorial.org/book/beginning#sec-heroku_commands

**Comment by mattzollinhofer** [comment]
Oh cool, I didn’t know that deploy to heroku section was there. That’ll tie in to #16 nicely. Doubt he’ll get into codeship, but codeship is definitely a nice-to-have ot a good distraction when you need it.

**Comment by mattzollinhofer** [comment]
I was just skimming though the rails tutorial again and thought of a couple things. 

1. Did you push this code anywhere on github for me to take a look at or did you just do it locally? If not, why don’t you create a repo and push up what you’ve got for me to take a look?

1. This tutorial does its testing using mini-test which is the rails default, BUT I don’t know mini-test really at all. Every project I’ve ever worked on has use the other major testing framework: rspec. I’d like for you to get familiar with that testing tool. So could you look that up and convert these test to rspec?

1. How did you feel about the test driven development approach?

1. Did you get guard running?

**Comment by tannerwernecke** [comment]
1. I did push each to my repo, but each are private. I can make each public though so you can have a look.
2. I can definitely take a look at it and convert to rspec.
3. I like the test-driven development approach. We did it occasionally at JMU and I find it to be helpful.
4. I got guard running, but the tutorial didn't work with it much, is that something I should look up separately as well?

**Comment by mattzollinhofer** [comment]
Yeah, having guard running while you’re developing can be really nice. It’s worth getting setup and used to using as you move forward.

**Comment by tannerwernecke** [comment]
I found an older version of the same walkthrough that uses rspec and goes more in-depth to guard. I will walk through that one tomorrow and convert to rspec and get guard setup!
https://rails-3-2.railstutorial.org/book/static_pages

**Comment by tannerwernecke** [comment]
@mattzollinhofer I'm struggling with rspec and keep getting errors that I can't diagnose. Not sure if you still had some time today to meet up. If not, I can work on other things and come back to it Monday when we meet.
