### ISSUE TITLE
Setup Dev Environment for Rails

### ISSUE THREAD

**Issue by mattzollinhofer** [iotait/apprenticeship#15]
* ruby/rails installed
* a working IDE

This is probably overlapped with the Rails Tutorial issue (#14)

**Comment by tannerwernecke** [comment]
Installed ruby/rails and started working with VSCode IDE because I am familiar with it. I would welcome your opinions on other IDE's or on VSCode.

**Comment by mattzollinhofer** [comment]
Awesome, great start. I'm totally good with VSCode, I've heard that RubyMine is a little more tailored to Rails dev work, I think it does a little better jumping through method calls for you, but VSCode is solid.
