### ISSUE TITLE
Write up Second Week Summary

### ISSUE THREAD

**Issue by mattzollinhofer** [iotait/apprenticeship#23]
I really appreciated week one's thoughts. Let's do it again. Feel free to change/add/remove questions:
- What did you accomplish?
- What did you get stuck on?
- What do you hope to do next week?

**Comment by tannerwernecke** [comment]
https://docs.google.com/document/d/19rzHmiEmhKvrn_aqEM4R1mJ1_DAy5CgmwbmmxnRixv8/edit?usp=sharing
