### ISSUE TITLE
Git branching

### ISSUE THREAD

**Issue by mattzollinhofer** [iotait/apprenticeship#6]
- https://learngitbranching.js.org

**Comment by tannerwernecke** [comment]
Was struggling some with these tutorials. Found and used two video walkthroughs to give me a better understanding and was able then to continue with the git branching exercises.

https://www.youtube.com/watch?v=QV0kVNvkMxc (branching)
https://www.youtube.com/watch?v=XX-Kct0PfFc (merging)

**Comment by tannerwernecke** [comment]
Worked through "Moving Work Around" in the "Main" section. Worked through "Push & Pull -- Git Remotes!" in the "Remote" section. Struggled to finish levels after those, if there's anything really important past that, I can search for other walkthroughs or help to finish them. However, if I've covered most important topics, then I'll spend time elsewhere that would be more valuable.
